name: CN Website Publish CI

on:
  # push:
  #   branches: [preview-script]
  pull_request:
    branches: [preview-script]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Website Next
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - run: cd site2/website-next && yarn install && yarn build
      - name: Publish Website Next Preview
        env:
          PREVIEW_PUBLISH_TOKEN: ${{ secrets.PREVIEW_PUBLISH_TOKEN }}
        run: cd site2/tools && sh preview-website-next.sh
